spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stargate_database
    username: postgres
    password: postgres01
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
